server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3406/web_homework?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: always
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
oss:
  accessKey: XMvu_u_7k-srFviD9fJ_1vzfMQpCRgUqozfLGSiH
  secretKey: o2DqTNW94Lmdbpk2McwiclWxOwQXNxbYxpvgAppg
  bucket: xy-web-homework
  testDomainName: http://scw4ktb48.hd-bkt.clouddn.com/
